# Generated by Django 3.1.3 on 2020-12-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileUpdate', '0002_auto_20201203_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='date_created',
            new_name='dob',
        ),
    ]
