# Generated by Django 3.1.3 on 2020-12-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileUpdate', '0003_auto_20201203_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='maxSeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
