# Generated by Django 3.1.3 on 2020-12-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_age', models.PositiveIntegerField()),
                ('passenger_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('journey_start', models.CharField(max_length=10)),
                ('journey_end', models.CharField(max_length=10)),
                ('date_of_journey', models.DateTimeField()),
                ('seat_no', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_order', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Compartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingPage.route')),
            ],
        ),
    ]
